### ISSUE TITLE
Better i18n support

### ISSUE THREAD

**Issue by RolandStuder** [joeldrapper/phlex#179]
Currently Phlex does not provide anything for i18n, one can include `I18n` and then use the translation helpers with absolute keys.

So while this works, adding the rails helpers for i18n will cause problems, when trying to use relative keys like `t(".new")`, it will raise an error, that there is no `@virtual_path` set.

ViewComponent solves this, by setting the `@virtual_path` in the `render_in` method. 

ViewComponent also supports having the language files as sidecar files, which is pretty neat, and might be a cool thing for Phlex as well.

Some of my research on the topic can be found here: https://discord.com/channels/629472241427415060/1002702966551216139/1022976024432095373

**Comment by joeldrapper** [comment]
> as you can see, it's easy to include, but you also need to provide the @virtual_path variable. What are your thoughts about this, I feel like i18n should work out of the box.

I agree. Translation should work out of the box when it's available in Rails.

> It's a bit annoying, that an instance var is required. So I actually think, one has to overwrite the new method, as POROs don't really provide any after_initialize or something like that, or is there something along those lines?

If we need to do this, we should be able to do it in the `Renderable#render_in` method which is always called when rendering in Rails.

I’m not sure how I feel about the side car files. I would rather move the translations inline like we've done with templates, though I’m open to optional side car files for people who need translations to be separate for translation service API compatibility, etc.

I don't really like the dot syntax `t("a.b.c") and would prefer something closer to dig `t(:a, :b, :c)` or even `t.a.b.c`, though I guess it makes sense to support the normal rails syntax for backwards compatibility even if we provide a cleaner API. For performance, the compiler could inline this as something like `@translations[:a][:b][:c]`.
