### ISSUE TITLE
Conversion of underscores to dashes should be configurable

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#18]
Currently, Phlex automatically converts underscores `_` to dashes `-` in CSS class output. This is because, while dashes are pretty standard for CSS classes (e.g. Tailwind), they are not allowed in Ruby Symbols / method names. I think this is a good default, but you should be able to disable it with a configuration option.

The conversion happens here https://github.com/joeldrapper/phlex/blob/main/lib/phlex/tag.rb#L56

Nothing else in Phlex is configurable yet, so it'll be necessary to setup some kind of configuration pattern at the same time. The interface should be something like this, which you could add to an initialiser in Rails.

```ruby
Phlex.configure do |config|
  config.convert_underscores_to_dashes = false
end
```

**Comment by saksham-jain** [comment]
Hey @joeldrapper, can you describe this enhancement. Also If this is not picked already by someone I would like to work on it.

**Comment by saksham-jain** [comment]
@joeldrapper  Man, please explain this enhancement a bit.

**Comment by joeldrapper** [comment]
@saksham-jain I've added some details to the issue. Let me know if you have any questions and thanks in advance for looking into this!

**Comment by saksham-jain** [comment]
@joeldrapper  Please allow me to push new branch, want to create PR for this.

**Comment by joeldrapper** [comment]
@saksham-jain you should be able to fork Phlex and open a PR from your fork.
