### ISSUE TITLE
Rails install generator

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#184]
- [ ] Create a Phlex initialiser for configuration
- [ ] Configure Tailwind if installed
- [ ] Configure autoload paths to include `app` #197

**Comment by alexandreruban** [comment]
I can work on this, but I have two questions:

> Create a Phlex initialiser for configuration

Do we agree there is nothing to configure yet? (lib/phlex/configuration.rb is empty)

> Configure Tailwind if installed

Do you have something specific in mind for this?

**Comment by joeldrapper** [comment]
Yeah, there's no configuration yet. I think we'll need to add some for the compiler soon but I don't think we need to do that yet. For Tailwind, we should update the configuration to include Ruby files in `app/views`.

Here's the default configuration in `config/tailwind.config.js`.

```js
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: [
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}',
    './app/content/**/*.{erb,haml,html,slim,rb}'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/typography'),
  ]
}
```

Ideally, we should at `rb` to this list `'./app/views/**/*.{erb,haml,html,slim}'`. Though I think it might be more reliable to simply add another item to the content array `./app/views/**/*.rb'`.
