### ISSUE TITLE
Lazy `tokens` evaluation

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#189]
Phlex tokens use Symbols / Procs for the condition statements. This means there's no requirement to execute the condition statements at definition. We can save them in a constant somewhere and apply them later.

For this to work, tokens would have to return a `Phlex::Tokens` object that can be coerced into a hash with `**`.

**Comment by fractaledmind** [comment]
You only need to define the `to_hash` implicit coercion method on the object.
