### ISSUE TITLE
Rename `content` method

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#190]
I would like to allow people to use an expose the `content` method as a “slot” for their component. For example, you might want to define a component that has slots for title and content. For example, you could define a `Card` component with `title` and `content` slots:

```ruby
class Card < Phlex::Component
  def template(&)
    article(&)
  end

  def title(text)
    h3 text, class: "title"
  end

  def content(&block)
    div class: "content", &block
  end
end
```

And this component could be used like this:

```ruby
class Example < Phlex::Component
  def template
    render Card do |c|
      c.title "Hi"

      c.content do
        p "Hello!"
      end
    end
  end
end
```

Supporting this means renaming the `content` method defined here:

https://github.com/joeldrapper/phlex/blob/bb358e7942749d7834f679bb8c6e54115d5616cd/lib/phlex/component.rb#L58-L67

This method yields self to the block but also captures the output of that yield as text content if the buffer wasn't changed by the yield. It's difficult to know what to call it.

**Comment by joeldrapper** [comment]
I think `yield_content(&)` might be a good option, but I'm open to other suggestions.

**Comment by fractaledmind** [comment]
`capture` perhaps?

**Comment by joeldrapper** [comment]
`capture` is already defined to return the string value from a block.

https://github.com/joeldrapper/phlex/blob/bb358e7942749d7834f679bb8c6e54115d5616cd/lib/phlex/component.rb#L127-L138

The funny thing is, `capture` would actually work as it is, because it would return a string without modifying the original buffer.
