### ISSUE TITLE
Fragment caching

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#2]
The cache key should include

- [x] User provided resource
- [x] Ruby version
- [x] Phlex version
- [x] Content block definition checksum
- [x] Relevant ancestors checksums
- [x] Sub component checksums
- [ ] Sub component checksums from the content block definition

**Comment by joeldrapper** [comment]
I’m re-working the fragment caching using `syntax_tree` to parse subcomponents and content blocks. This should make the cache versions a lot more precise so they’re invalidated less often. Also, the Ruby parsing will only happen once for each cached class before it's memoised.

**Comment by joeldrapper** [comment]
The work on fragment caching is on hold while I build out static components (#19). I think we may find that we only want to cache the resources themselves rather than templates, since static components are already incredibly fast. Caching only the resources would mean more cache keys could be shared and would drastically simplify things.

**Comment by joeldrapper** [comment]
No, the SyntaxTree will need to read the source files too. But the SyntaxTree compilation isn't quite the same as fragment caching. It'll just speed up the existing dynamic functionality that's already available. When using IRB, you should be able to get by with dynamic components and no caching.

**Comment by fractaledmind** [comment]
Gotcha. I was just trying to spin up a quick playground to explore the internals of the gem and bumped into not being able to explore any of the cacheing related internals without a separate file. No biggie for now tho. I'll just create that separate file and require it and go from there
