### ISSUE TITLE
Generator failed

### ISSUE THREAD

**Issue by klippas-rob** [joeldrapper/phlex#208]
I added `gem 'phlex'`  to the Gemfile and ran `bin/rails phlex:install`.
I then ran 

`bin/rails g phlex:view Card`

which resulted in:

`Could not find generator 'phlex:view'.`

Ruby 3.1.2
Rails 7.0.4

**Comment by joeldrapper** [comment]
Thanks for opening the issue. It looks like this bug was fixed by @alexandreruban in #205. I’ll ship a `0.3.1` patch today.

**Comment by joeldrapper** [comment]
@klippas-rob I just shipped `0.3.1` which should fix this issue. You might want to run `bin/rails phlex:install` again so it sets up an `ApplicationView` for you, since that's now included in the view generator.
