### ISSUE TITLE
1.0 Documentation

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#242]
## Guide
- [ ] Introduction
- [ ] Views
- [ ] Templates
- [ ] Helpers

## Standard library
- [ ] Collections
- [ ] Tables

## Rails
- [ ] Getting started
- [ ] Rendering views
- [ ] Layouts
- [ ] Helpers
- [ ] Migrating to Phlex

**Comment by stephannv** [comment]
What do you think about a "Testing" section? Something like Viewcomponent: https://viewcomponent.org/guide/testing.html
