### ISSUE TITLE
Tailiwind classes won't load

### ISSUE THREAD

**Issue by merongivian** [joeldrapper/phlex#243]
Hey, thanks for working on this!, really excited about the possibilities of having full components on rails a la react :)

Found an issue with tailwind classes that i think has not been reported: Lets say im using a tailwind class in phlex that i haven't used before in a normal haml/erb file, it won't be defined in the browser, but if i use it in a html view it 'detects it'. It seems its due to compilation not being done when adding tailwind classes in phlex

**Comment by joeldrapper** [comment]
Hey, you'll need to configure Tailwind to look at Ruby files in `app/views`. I believe @alexandreruban is working on adding this to the install script.

**Comment by merongivian** [comment]
I solved it by adding `rb` on the content folders checked in `tailwind.config.js` 😄
