### ISSUE TITLE
Should `ApplicationView` be a module?

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#253]
I’ve gone back and forth on this, but I’m starting to think `ApplicationView` should be a module that you include rather than a class to inherit from. `ApplicationView` itself should never be initialised, while abstract views might be things you can either initialize themselves or subclass and override. This is a tough call because the standard for everything else in Rails is to have an "ApplicationThing" that you subclass.

**Comment by dhnaranjo** [comment]
How about you keep `ApplicationView` but it just like...

```
class ApplicationView
  include Phlex::TheActualThing
end
```

Folks like me who would love to, for example, have my more simple components inherit from Sorbet `T::Struct`, could either have my own `ApplicationView` inherit from `T::Struct`, or not have one at all and just include the Phlex module where I wanted.

You could even have multiple composable modules. I could bring in the base for all my components, then bring in collection stuff when relevant.

**Comment by joeldrapper** [comment]
It would be handy to be able to use the new `Data` classes too.

```ruby
MyView = Data.define(:foo, :bar) do
  include Phlex::View
end
```

**Comment by joeldrapper** [comment]
Making `Phlex::View` a module will be quite challenging because it has a number of class-level concerns such as compilation and tracking whether a component class has been rendered before. I do think we should encourage making `ApplicationView` a module though.
