### ISSUE TITLE
Avoid template naming conflict

### ISSUE THREAD

**Issue by joelmoss** [joeldrapper/phlex#258]
Have you thought about renaming the `template` method to avoid conflicting with the HTML `<template>` tag? For example, `render`?

This would completely remove that gotcha/caveat, and also makes a little more sense from a naming POV.

**Comment by joeldrapper** [comment]
I have thought about it a lot and I haven’t been able to come up with a good name that isn't taken. The instance method `render` is used to render other things inside the template. `call` is part of the external API so doesn't make sense to define that directly. I’m not a fan of `build` or `perform`.

**Comment by evenreven** [comment]
Maybe it's because I know Vue a little, but because of Vue there's kind of a precedent for using template as the markup generating block in single file components. Sure, it's more correct in javascript land, but it still feels conceptually right to me. (Also, I think the conflict with the template element is pretty niche unless you use the template tag a lot, and when you write HTML with a Ruby DSL, I think adjustments are to be expected anyway.)

**Comment by joeldrapper** [comment]
It's worth noting that it is possible to correct `template` calls from inside the template method using the compiler. I just don't know if I want to go down that path because then it's not really Ruby anymore. It's a new language that operates slightly outside of the Ruby rules.

**Comment by joeldrapper** [comment]
I think this might be a way out. https://github.com/joeldrapper/phlex/pull/260

**Comment by joelmoss** [comment]
Oh nice! 👏

And as a happy side note, I think this should also work for #259...

```ruby
# ...
if block.instance_variable_get(:@rendering)
  respond_to?(:before_render) && before_render
  super(&block)
else
# ...
```

I still can't help but thinking that `render` would be a better name for the `template` method, and rename the internal methods that conflict.  But the above is ✨

**Comment by joeldrapper** [comment]
`render` is a verb, it's a "so something" method. `template` _conceptually_ doesn't do anything, it is something.

As things stand, we go through three methods to render a template and I think they're well named: when I _render_ a view, the view is _called_ and outputs its _template_.

**Comment by joelmoss** [comment]
When you describe it like that, it makes sense, but as far as a public API is concerned, the `template` method is all that matters, and I see that as I am rendering the content of the method that is currently called `template`. So a verb makes sense.

But hey, each to their own. You've already solved the template HTML tag conflict, so I'm happy 👏

thx

**Comment by joeldrapper** [comment]
Naming is hard.

**Comment by joelmoss** [comment]
Oh don't remind me 😫

**Comment by joeldrapper** [comment]
I’ve closed #260. I’ll keep this issue open until `1.0` if anyone wants to suggest another approach or alternative name.

**Comment by joeldrapper** [comment]
You know if we pick one of these, within hours there'll be an update to the HTML spec adding a tag by the same name. 🙃

**Comment by stephannv** [comment]
> You know if we pick one of these, within hours there'll be an update to the HTML spec adding a tag by the same name. 🙃

🤣 The html maintainer is watching this thread.

Btw, I think `template` is a good name, I think it's a pain you can live with. An alternative would be `call` to define structure (like some service objects, interactors, etc) and rename the current `call` method to another name

**Comment by evenreven** [comment]
I used to think `template` was perfect even though the template tag exists, but `markup` is growing on me. `def markup` is kinda what the method does, isn't it? It literally defines what the markup of the component will be.

**Comment by joelmoss** [comment]
I was actually just about to +1 on `markup`. It's kinda like `template`, but _**H**yper**T**ext**MarkupL**anguage_ 😄

**Comment by joeldrapper** [comment]
What about `phlexml`? 🙃

**Comment by joeldrapper** [comment]
I actually [found a way](https://www.theabstraction.space/p/magic-template-methods) to get the `template` method to work, but it's slow. If the compiler turns out to be as reliable as I hope it will be, we could use this slow technique but then optimise it in the compile step.

**Comment by joelmoss** [comment]
OMG 😱 I love it! 🤣

**Comment by joelmoss** [comment]
If the compiler does it's job, then I would guess we wouldn't have to worry about performance as much.

**Comment by joeldrapper** [comment]
> If the compiler does it's job, then I would guess we wouldn't have to worry about performance as much.

Right, the compiler can completely remove this problem as long as we can solve it (slowly) without it. I’m just not confident enough that the compiler will be reliable enough to commit to it yet, but it's looking good so far.
