### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by joelmoss** [joeldrapper/phlex#259]
Would be great if there were a way to call something before and/or after rendering. Happy to create a PR if you agree.

**Comment by joeldrapper** [comment]
What's the use-case out of interest? Here's one pattern you can use already.

```ruby
class AbstractView < Phlex::View
  def template(&)
    do_somethign
    yield_content(&)
    do_something(&)
  end
end

class ConcreteView < Phlex::View
  def template
    super do
      # things here
    end
  end
end
```

**Comment by joelmoss** [comment]
Yeah I want to avoid having to remember additional code within the `#template` method. It's easy to forget the `super`. As in most cases I will want to before callback to run on all views. I still want to write:

```ruby
def template
  h1 'my view'
end
```

My primary use case is side loading JS and CSS assets along side each view, which simply needs to make a call immediately before `template` is run.

**Comment by joeldrapper** [comment]
How are you thinking of implementing this? I don't want it to impact performance too much, which is quite difficult at this point.

I was originally thinking the best-case performance impact will be one additional method call. We wrap the `template` method and call a different method from `call` instead.

```ruby
def around_template
  template
end
```

But I think we can do even better than this when no callbacks are defined for a view. If we define `around_template` as a `template` alias, it will be as fast as calling the original. Then we only define `around_template` for views that actually have callbacks.

**Comment by joelmoss** [comment]
Already implemented at https://github.com/joelmoss/proscenium/blob/master/lib/proscenium/view_component.rb#L12-L14 and https://github.com/joelmoss/proscenium/blob/master/lib/proscenium/side_load.rb.

This won't affect perf, as all it does is track side loaded asset paths, and render `<script>` and `<link>` tags in my layout when needed.

`around_template` would work, but would fall down when subclassing further, and multiple callbacks are needed/registered. I suppose something akin to ActiveSupport::Callbacks would be ideal.

**Comment by joeldrapper** [comment]
I think it should be okay as long as you always call `super` from `around_template`. But yeah, `around_template` could have an implementation when it's defined to execute a list of before and after callbacks.

**Comment by joelmoss** [comment]
> I think it should be okay as long as you always call super from around_template

Yeah that's reintroducing the problem we sought we solve though. It's extremely easy to forget `super` 😏

**Comment by joeldrapper** [comment]
I think we could do something like this in `Phlex::View#call`.

```ruby
before_render if respond_to?(:before_render)
template(&block)
after_render if respond_to?(:after_render)
```

**Comment by joelmoss** [comment]
LGTM 👍 and means I don't have to call super all the time

**Comment by joeldrapper** [comment]
You'd still have to call super if you wanted to stack before / after callbacks from super classes.

I’m trying to find a way to drop the 1% hit, since it affects everything. I think perhaps we could allow you to include a module for access to callbacks.

```ruby
class Card < Phlex::View
  prepend Phlex::Callbacks

  def before_render
    do_something
  end

  def template
    ...
  end
end
```

**Comment by joelmoss** [comment]
> You'd still have to call super if you wanted to stack before / after callbacks from super classes.

Ah good point, but I think that's acceptable

**Comment by joeldrapper** [comment]
I think the best way to do this will be to have a `Phlex::View::Callbacks` module that you can `prepend`.

```ruby
module Phlex::View::Callbacks
  def template(&block)
    before_render if respond_to?(:before_render)
    super(&block)
    after_render if respond_to?(:after_render)
  end
end
```

Then you could use it like this:

```ruby
class Card < Phlex::View
  prepend Phlex::View::Callbacks

  def before_render
    do_something
  end

  def template
    ...
  end
end
```

**Comment by joelmoss** [comment]
Super simple! ❤️

**Comment by joeldrapper** [comment]
@joelmoss do you want to work on this? It'll need tests and documentation, but I expect the above should work really well.

**Comment by joelmoss** [comment]
Yeah sure, will try and get to it this week.

**Comment by joelmoss** [comment]
Thinking more on this, and I'm not so sure that `before_render` and `after_render` are the right names.

Based on when they get called - immediately before and after `template` is called - I think perhaps they should be `before_template` and `after_template`. Especially `after_render`, which is not actually called after rendering at all.
