### ISSUE TITLE
Capture still rendering block

### ISSUE THREAD

**Issue by joelmoss** [joeldrapper/phlex#268]
'm trying to use `capture` to assign a block to a variable for later usage. I need to do this so that the captured block is called first, but not rendered until later...

```ruby
class Layout < Phlex::View
  def template(&)
    html do
      _body = capture { main(&) }

      head do
        title { 'My Site' }
      end
      @_target << _body
    end
  end
end

class Page < Phlex::View
  def template
    render Layout.new do
      h1 { 'Home' }
    end
  end
end
```

What should be rendered as:

```html
<html>
  <h1>Home</h1>
  <head>
    <title>My Site</title>
  </head>
  <main></main>
</html>
```

should be:

```html
<html>  
  <head>
    <title>My Site</title>
  </head>
  <main>
    <h1>Home</h1>
  </main>
</html>
```

So when I call `capture`, it is rendered and not actually captured.

However, all is well when I call capture without a predefined block:

```ruby
_title = capture { title { 'My page' } }
```

help is appreciated, thx.

**Comment by joeldrapper** [comment]
Hey Joel, the reason this doesn't work is the `#h1` call happens on the `Page` view not the `Layout` view. This is so instance variables and methods from the `Page` can be used in the block.

`capture` works by temporarily swapping the target output buffer with a new one and returning that at the end of the closure after putting the original target back. This target replacement is local to the `Layout` where `#capture` was actually called.

It might help if I could understand why you need to yield the block without rendering it as there might be another way forward.

**Comment by joelmoss** [comment]
Every view can have "side loaded" assets (js, css), which are only side loaded if they exist. I then need to load these assets with script or link tags. For js they will be at the end of the body. But for css, the link tags need to be in the head.

And herein lies the problem. The head block obviously needs to render before the body. But until the body has been rendered, I won't know what has been side loaded. 

So my idea was to assign the body to a variable before the head renders. Then I can return/render the body after the head, and know about all my side loaded assets

Hope that explains it.

**Comment by joeldrapper** [comment]
That makes a lot of sense. I'll see if I can find a way to get this to work.

**Comment by joeldrapper** [comment]
This is really tricky because the top part of layout is rendered before the page. This means we can stream parts of the layout before the rest of the content has even been built, but it precludes the option of retrospectively inserting things in the `<head>`.

Before we look into solutions (and I have a few ideas), would it not be possible to output your script / link tags in the `<body>` when the requirement for them is first encountered? It's not commonly done, but it's valid HTML and supported by all browsers as far as I can tell.

**Comment by joelmoss** [comment]
For the JS in script tags, they can (usually) be loaded anywhere. But for css in link tags, particularly critical css, they have to be in the head, otherwise, you end is with a flash of unstyled content until the css has loaded. There are also other tags that I will sometimes need to insert in the head.

The above is a requirement I'm afraid. 

Another idea is to record all the views that have or will be rendered. That will be enough for me to figure out what to side load. I'm only interested in the views. 

However, I can see how the ability to capture a block could be useful for other things too.

**Comment by joeldrapper** [comment]
True, FOUSC could be a problem if the styles are critical.

One option is to write a placeholder out to the target and then gsub it later. You could implement this yourself but I could also see this as a first party feature.

```ruby
class Layout < Phlex::View
  def template(&)
    html do
      head do
        title { 'My Site' }
        text "[HEAD_PLACEHOLDER]"
      end
      main(&)
    end
  end
end

class Page < Phlex::View
  def template
    render Layout.new do
      h1 { 'Home' }
      @_target.gsub "[HEAD_PLACEHOLDER]" capture {
        link rel: "stylesheet", href: "from_home"
      }
    end
  end
end
```

When it comes to streaming, if this was a first-party feature, the buffer could stream up to the placeholder and then wait until it is fulfilled.

**Comment by joeldrapper** [comment]
You should probably use `comment` instead of `text` for the placeholder in case it's not replaced for some reason.

**Comment by joelmoss** [comment]
ok, i think that would work. I'll have a play with that. thx

**Comment by joeldrapper** [comment]
@joelmoss let's close this, I don't think `capture` should change. Let me know how you get on with the placeholder gsub though. That's a really interesting idea for a feature.

**Comment by Bumppoman** [comment]
```ruby
block.binding.receiver.instance_variable_set("@context", self)
content = capture(&block)
```

I found this to work in a limited capacity for what I needed.  Not sure if it's helpful to anyone else.
