### ISSUE TITLE
Update the `_attributes` method to take keyword arguments

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#297]
The `fetch_attrs` method won't be necessary if the `_attributes` method takes keyword arguments instead of a positional hash argument.

**Comment by joelmoss** [comment]
So I'm a little concerned that after removing the `fetch_attrs` method, all tests still pass 🤔 including those which still call that method.

I'm not familiar enough with the compilation stuff to be confident that all still works, especially considering all tests still pass, even though they are calling a method that no longer exists.

**Comment by joeldrapper** [comment]
Oh, that's because the tests test that it compiles to call `fetch_attrs` but none of the tests actually execute the compiled code just yet. You should be able to do a find / replace for `fetch_attrs` -> `process_attributes`.

**Comment by joeldrapper** [comment]
Compilation is experimental at this point, so doesn't matter if it breaks.
