### ISSUE TITLE
Security risk with `process_attributes` override

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#301]
@joelmoss I’ve just realised a possible problem with encouraging people to override `process_attributes`. If you don’t call `super` but return a String instead, you lose a bunch of security features.

I wonder if we should go back to the idea of having `process_attributes` called from `_attributes` so the attributes are always filtered. What do you think?

**Comment by joelmoss** [comment]
Oh the joys of forgetting 'super' 😩

I would always prefer not having to worry about super, but you you've been quite persistent on maintaining performance.

I suppose we have to pick our battles, and consider if it's a minor perf hit.

**Comment by joeldrapper** [comment]
Yeah, I think we should take the performance hit unfortunately.

**Comment by joelmoss** [comment]
It should be a very very minor hit. 

I'll get you a new PR

**Comment by joelmoss** [comment]
You wanna keep the kwargs change in `_attributes`?
