### ISSUE TITLE
render_view should return document, not fragment

### ISSUE THREAD

**Issue by joelmoss** [joeldrapper/phlex#304]
`Phlex::TestHelpers#render_view` returns a Nokogiri fragment, which is not useful when wanting ti test against the full document.

I think instead of `Nokogiri::HTML.fragment(rendered)`, `Nokogiri::HTML(rendered)` would be better, as that returns the entire document.

For example, `have_css('head > link[rel="stylesheet"]')` on the fragment will fail, while it will work on the document.

**Comment by stephannv** [comment]
The problem with `document` is it returns a HTML page, instead a html snippet. 
Using fragment it is possible to do something like this:
```ruby
# my component
class MyCard
  def template
    # ...  some code
    render StatusBadge.new(item: item)
    # ... some code
  end
end

# tests
it "renders status badge" do
  item = Item.new(...)
  result = render_view(MyCard.new(item: item))
  status_badge = render_view(StatusBadge.new(item: item))
  
  expect(result).to include(status_badge) # it will fail if status_badge is a document instead a fragment
end
```

One solution is to create a new helper, eg.: `render_page`, `render_layout`, returning a document instead a fragment.

**Comment by joelmoss** [comment]
I suppose the challenge is knowing whether the view is a full HTML page (with <html>, <head>, <body>, etc.), or just a fragment (an HTML element). A Phlex view can be anything.

I'm not sure different methods would be great - that could be confusing for newcomers. Perhaps `render_view` could accept a keyword argument (`as:`), which could have a value of either `page` or `fragment`. And perhaps with a sensible default?

```ruby
render_view MyCard.new(item: item), as: :page
render_view StatusBadge.new(item: item), as: :fragment
```

**Comment by joeldrapper** [comment]
@joelmoss @stephannv I wonder if we should remove Nokogiri support and just support Capybara instead. What do you think? Are there any advantages to direct Nokogiri integration? Of course anyone could make a plugin — but I don't know if we should ship it in Phlex.

**Comment by joelmoss** [comment]
I'm actually only using Nokogiri, simply because I think capybara is overkill. And besides, capybara uses Nokogiri under the hood anyway.

**Comment by joeldrapper** [comment]
How does ViewComponent handle this issue with fragments vs documents? I guess it's not an issue for them because they don't recommend using view component for the whole page.

**Comment by joelmoss** [comment]
They render as a Fragment. But yes, that makes sense, as they focus on components, not pages.

[This is nice](https://github.com/ViewComponent/view_component/blob/main/lib/view_component/test_helpers.rb#L10-L12) though - it allows for Capybara assertions to be used.

**Comment by stephannv** [comment]
> They render as a Fragment. But yes, that makes sense, as they focus on components, not pages.
> 
> [This is nice](https://github.com/ViewComponent/view_component/blob/main/lib/view_component/test_helpers.rb#L10-L12) though - it allows for Capybara assertions to be used.

It's already possible to use capybara assertions, because matchers convert the object to capybara node:
```ruby
result = render_view(MyComponent.new)

expect(result).to have_link("Contact", href: "/contact") # capybara matcher
```

The `page` is useful when you are doing this:
```ruby
def test_my_component
  render_view(MyComponent.new)

  assert_link "Contact", href: "/contact" # capybara will use `page` 
end
```

The `page` was being implemented in these PRs https://github.com/joeldrapper/phlex/pull/282 and https://github.com/joeldrapper/phlex/pull/278.

About fragments vs documents, I think assert against head tag is a edge case, we can add to the docs a suggestion:
```ruby
# If you want assert against html, head and body tags, you can do this:
result = Nokogiri::HTML(view.call)
# If you are using Rails
result = Nokogiri::HTML(view.call(view_context: controller.view_context))

# If you are writing this code a lot you can create a custom helper, eg.
module Phlex
  module CustomHelpers
    def render_document(view)
      Nokogiri::HTML(view.call(view_context: controller.view_context))
    end
  end
end

RSpec.configure do |config|
  config.include Phlex::CustomHelpers, type: :view
end
```

**Comment by joelmoss** [comment]
> About fragments vs documents, I think assert against head tag is a edge case

I definitely disagree with that. The head can contain a lot of important stuff, and it usually matters if what you are testing for exists in the head or the body.

**Comment by stephannv** [comment]
> > About fragments vs documents, I think assert against head tag is a edge case
> 
> I definitely disagree with that. The head can contain a lot of important stuff, and it usually matters if what you are testing for exists in the head or the body.

On second thought, I really think I was wrong in my statement, and I agree with you. I said that thinking that complete pages (with html, head, body tags) are usually tested with integration/feature/system tests. But you are testing just the layout shell, makes sense to do unit tests, asserting head tags.

**Comment by joelmoss** [comment]
One idea that I'm exploring is distinguishing between a page, and a component, where both are Phlex views, but have different responsibilities and behaviour, especially when it comes to Rails.

A page would usually be rendered from a controller action, and a component would replace partials, and be used within one or more pages.

When you think like this, testing becomes clearer, as you know want to test against a Fragment for components, and a document for pages.

**Comment by stephannv** [comment]
> One idea that I'm exploring is distinguishing between a page, and a component, where both are Phlex views, but have different responsibilities and behaviour, especially when it comes to Rails.
> 
> A page would usually be rendered from a controller action, and a component would replace partials, and be used within one or more pages.
> 
> When you think like this, testing becomes clearer, as you know want to test against a Fragment for components, and a document for pages.

Yeah, in my pet project I'm doing this:
<img width="225" alt="Screen Shot 2022-11-02 at 14 58 46" src="https://user-images.githubusercontent.com/3025661/199566121-3443a3de-ca48-4990-aa77-cb4c2d5d12ef.png">

In controller: 
<img width="861" alt="Screen Shot 2022-11-02 at 14 59 37" src="https://user-images.githubusercontent.com/3025661/199566430-8141b0ba-5994-4e6e-a341-70211cb604e8.png">

I'm using feature/system tests to test high-level behavior: "i click here, render this, fill that, expect to have some content". And I'm using unit tests to test some specific compoment behaviors that would be very expensive to do cover all scenarios with integration tests, eg.: "When post is draft, renders Draft badge, when is published, renders Published badge", "when user has admin permission, navbar should render admin menu", etc.

**Comment by joeldrapper** [comment]
I wonder if we could detect whether a view is a document or not by detecting a call to `html`. For this, we'd need a global render context.

**Comment by joeldrapper** [comment]
We have helpers for Nokogiri documents and fragments now.
