### ISSUE TITLE
Custom form builder isn't working after changes in FormWith module

### ISSUE THREAD

**Issue by stephannv** [joeldrapper/phlex#327]
I was using phlex 0.4.0 in my app, with custom form builder. When I upgraded to use `main` branch, my forms stopped working. I guess this change broken it (https://github.com/joeldrapper/phlex/pull/319).

```ruby
class MyFormBuilder  < ActionView::Helpers::FormBuilder
  def my_text_field(attribute, **options)
    text_field(attribute, class: "input input-bordered"
  end
end

module Views
  module Form < ApplicationView
    include Phlex::Rails::Helpers::FormWith

    def template
      form_with url: "test", builder: MyFormBuilder do |f|
        f.my_text_field :name # 🚨 this field isn't being rendered
        f.text_field :name # ✅ this field is rendered 
      end
    end
  end
end
```

I'm opening a pull request with failing test case.

**Comment by joeldrapper** [comment]
Supporting custom `form_with` form builders is going to be really hard as we don't know which methods are meant to be output and which ones are just meant to return something. When you use ERB, this determination is done when you use the `<%=` tag.

**Comment by joeldrapper** [comment]
I think the only solution will be to switch to a Phlex form builder, e.g. #214.

**Comment by Bumppoman** [comment]
> I think the only solution will be to switch to a Phlex form builder, e.g. #214.

This is what I have done.  The only drawback is losing `fields_for` support, but that can obviously be fixed when I have some more time.

**Comment by joeldrapper** [comment]
Oh yes! We should be able to fix that pretty easily.

**Comment by joeldrapper** [comment]
@stephannv do you think you'd be able to switch to the `Phlex::Rails::Form` builder? I can't think of a way to make custom "form with" form builders work since we can't know which methods should be output to the buffer and which should just return something.

**Comment by stephannv** [comment]
My solution for now was:
```ruby
# config/initializers/phlex.rb
%i[money_field].each do |method_name|
  Phlex::Rails::Helpers::FormWith::BufferedFormWith.alias_method method_name, :__output_method__
end
```

**Comment by joeldrapper** [comment]
You could definitely get it working with your own `Phlex::Buffered`. 👍 I’d like to bring all those QoL features into `Phlex::Rails::Form` too.

**Comment by joeldrapper** [comment]
Thank you @stephannv. I’m going to keep working on `Phlex::Rails::Form` for now and close that PR, but if the issue comes up again and there's enough demand, we can re-open it. At least you've got a solution that works for you at the moment.

**Comment by tcannonfodder** [comment]
> @stephannv do you think you'd be able to switch to the `Phlex::Rails::Form` builder? I can't think of a way to make custom "form with" form builders work since we can't know which methods should be output to the buffer and which should just return something.


I wonder if a specific `buffer_output` method would be a good middle ground here? Essentially: "I, as the implementor of this Phlex component (& likely the FormBuilder), know that this is supposed to be buffered output". This would behave similarly to `raw_output`, I imagine; I wonder if there's any way we can add safety checks. Maybe the object needs to respond to `html_safe?`
