### ISSUE TITLE
Support custom elements

### ISSUE THREAD

**Issue by jaredcwhite** [joeldrapper/phlex#33]
I'm excited to see how this library evolves! One thing I was wondering is the ability to support custom element tags (aka arbitrary tag names with at least one dash).

I worked on a [PR for Papercraft](https://github.com/digital-fabric/papercraft/pull/2) to support converting Ruby calls like `my_custom_element` to `my-custom-element` and would be happy to contribute here if you have an approach in mind.

**Comment by alexandreruban** [comment]
There are two types of elements in Phlex:

- [Standard elements](https://github.com/joeldrapper/phlex/blob/main/lib/phlex/tag/standard_element.rb) like `div`, `a`, or `em` that have closing tags.
- [Void elements](https://github.com/joeldrapper/phlex/blob/main/lib/phlex/tag/void_element.rb) like `img` or `meta` that self closing.

Those elements are converted in methods in the [context](https://github.com/joeldrapper/phlex/blob/main/lib/phlex/context.rb) using `class_eval`. We define those methods explicitly in the context as `method_missing` is not very performant.

To keep this architecture, we could maybe register our custom elements:

```rb
Phlex.register_custom_element(:custom_element)

# Can custom elements be self-closing?
# In that case, we might have 
# Phlex.register_standard_element
# Phlex.register_void_element
```

What do you think? Do you think registering custom elements will be tedious if there are too many of them?

**Comment by jaredcwhite** [comment]
@alexandreruban @joeldrapper Registering sounds fine. Would that be something a component itself could do (i.e. if it's reusable across multiple projects)?

FYI custom elements can't ever be void.

`<my-tag />` 🚫
`<my-tag></my-tag>` ✅

**Comment by alexandreruban** [comment]
> Would that be something a component itself could do (i.e. if it's reusable across multiple projects)?

Maybe we can start with registering explicitly the component, what do you think? As Joel said: "I don’t think custom elements should be auto-defined whenever a missing method is called because that would make it more difficult to spot errors in component templates."

> FYI custom elements can't ever be void.

Nice! Thanks for the info!

**Comment by joeldrapper** [comment]
I think it makes sense for a component to be able to register a custom element that it can use locally but I’m also fine with having a global registry of custom elements.

**Comment by joeldrapper** [comment]
@jaredcwhite I’d be interested in your thoughts on this prototype? https://github.com/joeldrapper/phlex/pull/38/files#diff-21a6c3842cec52cec34f221fd3e9c2a68596c8c68cc22b2370a333c97c28640a
