### ISSUE TITLE
Support .html.phlex files

### ISSUE THREAD

**Issue by natematykiewicz** [joeldrapper/phlex#34]
If I’m understanding how Phlex works, in order to use it in Rails you will either need to call `render` in the controller and hand it a Phlex component, or embed a Phlex component in an erb, slim, or haml file. That got me thinking, what if Phlex supported .html.phlex files so that Phlex files could live in app/views. I’m thinking they’d be fairly similar to Jbuilder files then. They’d be anonymous components instead of named, and basically be what you see in the `template` functions in the examples.

You could support blocks with a yield, to nest templates (just like partials), and they’d have access to instance variables set in the controller.

Take this example from the documentation:
```ruby
class NavComponent < Phlex::Component
  def template
    nav id: "main_nav" do
      ul do
        li { a "Home", href: "/" }
        li { a "About", href: "/about" }
        li { a "Contact", href: "/contact" }
      end
    end
  end
end
```

Now imagine this:
```ruby
# app/views/things/show.html.phlex
nav id: "main_nav" do
  ul do
    @links.each do |link|
      li { a link.text, href: link.url }
    end
  end
end
```

I feel like it could help gain traction if people could still define views in a way they’re used to (app/views, with a DSL instead of defining a class). This would make it more of a direct competitor with ERB, Slim, and HAML then.

Under the hood, I imagine Phlex would define a constant for this based on the path. Like `Phlex::RailsViews::Things::Show` or something.

My thought is, if it’s a reusable thing, devs would give it it’s own name and put it in `app/components` or something. But if it’s just a view for a specific page, this anonymous form seems simpler, and more Railsy (and intentionally not easily reusable), but still defines the component with Ruby.

**Comment by joeldrapper** [comment]
I don’t think it’s worth defining a new file format for anonymous Phlex components if it would only be applicable to components that don't accept arguments. We can re-open this if we find a more compelling use-case.

**Comment by natematykiewicz** [comment]
I think one thing that would be good is adding a section to the README that gives an example of how you'd use this in Rails. How do you go from a controller action, to rendering HTML that's a Phlex component?

I think that's the crux of what I wanted to solve, and just (wrongfully) assumed that a .html.phlex file was the answer.

**Comment by natematykiewicz** [comment]
Or is the assumption that you'd still render a .html.erb file, and pieces of that would render a Phlex component (similar to how ViewComponent works)?

**Comment by joeldrapper** [comment]
We haven't finished the Rails documentation yet, but you should be able to just do this from your controller.

```ruby
class ArticlesController < ApplicationController
  def index
    render Views::IndexPage.new(
      articles: Article.all.load_async
    )
  end
end
```

**Comment by natematykiewicz** [comment]
Well that seems simple enough, and would work nicely `respond_to` as well:

```ruby
class ArticlesController < ApplicationController
  def index
    articles = Article.all.load_async

    respond_to do |format|
      format.json { render json: articles }
      format.html { render Views::IndexPage.new(articles) }
    end
  end
end
```
