### ISSUE TITLE
`nil is not a class/module' when including Phlex::Rails::Layout

### ISSUE THREAD

**Issue by Bumppoman** [joeldrapper/phlex#340]
Phlex 0.5.  The new lib/phlex/rails.rb loader seems to have introduced the above error somehow.  No other changes to my code besides the Phlex upgrade.

**Comment by joeldrapper** [comment]
Oh no! I think this is becuase I forgot to document that you need to require `phlex/rails` now. The best way to do this is from the Gemfile.

```ruby
gem "phlex", require: "phlex/rails"
```

**Comment by Bumppoman** [comment]
All set, thanks for the quick response 👍🏻

**Comment by joeldrapper** [comment]
Great! I’ve added that to the setup guide and noted it in the release. The website is deploying now with the new details.
