### ISSUE TITLE
Changes to `text` method resulting in content not being output

### ISSUE THREAD

**Issue by Bumppoman** [joeldrapper/phlex#393]
Perhaps this is intentional but it feels like a step backward.

Before 1.0.0-rc1, the following worked as expected:

```ruby
class Test < Phlex::HTML
  def initialize(object) = @object = object # @object is an ActiveRecord model object that responds to #to_s

  def template
    text @object
  end
end
```

Now, each such call needs an explicit `to_s` added or no content is output.

Again, this could be intentional and my misunderstanding, but I thought the primary use of `text` was to guarantee output where it might not otherwise happen.  Is this incorrect?

**Comment by joeldrapper** [comment]
I don't want to output *anything* that can be represented as a String with `to_s`.

Take this view for example.

```ruby
class Example < Phlex::HTML
  def initialize(items) @items = items

  def template
    @items.each do |item|
      h1 { item }
    end
  end
end
```

If we send it an Array of items.

```ruby
render Example.new([1, 2, 3]
```

We'll get
```ruby
<h1>1</h1>
<h1>1</h1>
```

**Comment by Bumppoman** [comment]
So your example doesn’t use `text`… I take your point about not wanting to automatically output anything as a string, but what would be the reason for wanting `text @object` to have no output?  It would seem that by calling `text` you’re declaring that you expect some output, right?

**Comment by joeldrapper** [comment]
That’s a good point, the behavior of `text` could be different to the implicit output from a block.
