### ISSUE TITLE
Cannot `yield` other objects from Phlex component

### ISSUE THREAD

**Issue by bschrag620** [joeldrapper/phlex#403]
In doing some work to build out a rails style form, I had originally implemented a pattern that involved yielding an object other than self inside the form. This was allowing for a `fields_for` method that could add scopes to the input names. The yielded object when calling a form wasn't actually the form itself, but instead for FormFields object. FormFields was handling then the rendering for the various input types.

```
Form.new(user) do |f|
  # inputs will have a name of "user[<input-name>]"
  f.text_input 'username'
  f.password_inpute 'plain_text_password'
  f.fields_for :address |ff|
    # now `ff` inputs will have a name of "user[address][<input-name>]"
    ff.street_address
    ff.city
  end
end
```

However, with [this](https://github.com/bschrag620/phlex/commit/282819b44179fdf11b8e06adc14d03275d649389) change that is no longer supported since `yield_content` always returns `self`. I'm proposing (and have it functioning locally) a change that allows `yield_content` to receive an object to be yielded. I'm just not certain if it is a pattern (a component yielding something other than itself) that should be supported. Happy to submit the PR for consideration if this seems like something that should be supported.

**Comment by joeldrapper** [comment]
Thanks for opening this issue. I think it should be supported, but we should implement it with a specialised `yield_content_with_args` method since it will be a significant performance overhead to introduce `*args` here.

If `call` takes args from `template`, it can pass them to this new method.

```ruby
around_template { template { |*args| yield_content_with_args(*args, &block) } }
```
