### ISSUE TITLE
Experimental feature warning is pretty dang annoying. Disable somehow?

### ISSUE THREAD

**Issue by dhnaranjo** [joeldrapper/phlex#404]
This really ought be configurable. Like, I get wanting people to see the warning, but ok, I've seen it, I accept this risk.
<img width="965" alt="image" src="https://user-images.githubusercontent.com/536280/205410639-e4477b7d-70f1-4625-8833-de9272857ab7.png">

**Comment by sisodiaa** [comment]
When I am trying to disable the experimental feature warnings by declaring configuration as mentioned above in an initializer file for my rails application, I am encountering `undefined method 'configure' for module Phlex (NoMethodError)`.

I am using phlex-rails (1.2.1) gem which have phlex (1.10.3) gem as dependency, and warnings I am getting are for `Phlex::Kit`.
