### ISSUE TITLE
unsafe_raw with helper that returns nil gives LocalJumpError (no block given)

### ISSUE THREAD

**Issue by djfpaagman** [joeldrapper/phlex#416]
I'm using [`vite-rails`](https://vite-ruby.netlify.app/guide/rails.html#tag-helpers-%F0%9F%8F%B7) in a new project together with Phlex. They supply a few helpers to set up the assets:

```ruby
<%= vite_client_tag %>
<%= vite_javascript_tag "application" %>
<%= vite_stylesheet_tag "application" %>
```

I use them in my Phlex layout like so:

```ruby
unsafe_raw helpers.vite_client_tag
unsafe_raw helpers.vite_javascript_tag "application"
unsafe_raw helpers.vite_stylesheet_tag "application"
```

The first helper, `vite_client_tag` can return `nil` when the vite dev server is not running (in production or when you dont' explicitly start it in development):

https://github.com/ElMassimo/vite_ruby/blob/41441af83f5cf3b3d02dcdd01fee4aaa1b564a07/vite_rails/lib/vite_rails/tag_helpers.rb#L7

This leads to a `no block given`, since `unsafe_raw` expects either some content or a block:

https://github.com/joeldrapper/phlex/blob/b3324fa7ffdc4b65586ac3fec1b8df6eaa9eef4a/lib/phlex/html.rb#L227

I've fixed it for now with `unsafe_raw helpers.vite_client_tag if helpers.vite_client_tag`, but I think it's fair to assume that helpers can return nil without a block. 

I'm not sure what the correct fix is performance wise, would a simple `if block_given?` check be sufficient?

**Comment by joeldrapper** [comment]
I think it should be reasonable to change `unsafe_raw` to just this. I can't remember exactly why it accepts a block, but I have a feeling it was to get around something that isn't an issue anymore.

```ruby
def unsafe_raw(content)
  return nil unless content
  @_target << content
end
```
