### ISSUE TITLE
Add scoped t(...) helper

### ISSUE THREAD

**Issue by mikker** [joeldrapper/phlex#457]
By starting your translation key with a `.` in controllers and views, Rails scopes it to the context. Ie. in `app/controllers/users/projects_controller.rb`, `t('.title')` would look up `t('users.projects.title')`.

I'm currently doing this like so in my `ApplicationView`. Happy to write a test and create a PR if this is something you see useful to add.

```ruby
def t(key, **opts)
  if key.starts_with?('.')
    scopes = self.class.to_s.underscore.gsub('/', '.')
    key = "#{scopes}.#{key}"
  end

  I18n.t(key, **opts)
end
```

Reference
* [ActionController implementation](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/actionpack/lib/abstract_controller/translation.rb#L17)
* [ActionView implementation](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/actionview/lib/action_view/helpers/translation_helper.rb#L73)

**Comment by joeldrapper** [comment]
You can install this `phlex-translation` and include `Phlex::Translation` to access scoped translations like this.

Take a look at how it's implemented here. https://github.com/joeldrapper/phlex-translation/blob/main/lib/phlex/translation.rb

**Comment by joeldrapper** [comment]
Also, if you have any suggestions for improvements to that, please open an issue or PR. I haven't had much time to work on that extension yet.

**Comment by mikker** [comment]
That's perfect!

```ruby
class Views::ApplicationView < Phlex::HTML
  include Phlex::Translation

  private

  def t(key, **opts)
    translate(key, **opts)
  end
end
```

**Comment by joeldrapper** [comment]
You could just do this which would be one less method call when using it.

```ruby
alias_method :t, :translate
private :t
```
