### ISSUE TITLE
undefined method for route helpers

### ISSUE THREAD

**Issue by cromega** [joeldrapper/phlex#471]
Running
* phlex 1.3
* phlex-rails 0.4.2

Using a route helper in a phlex view gives me 
```
undefined local variable or method `default_url_options ' ...
```

if I use `helpers.<path helper>` , it works fine.

Wondering if the include in `ApplicationView` is not needed anymore?

**Comment by joeldrapper** [comment]
Including `Rails.application.routes.url_helpers` only works for some paths. We should remove this from the `phlex-rails` generators and advise using `helpers.path_helper` instead. There's an issue for this here. https://github.com/joeldrapper/phlex-rails/issues/28
