### ISSUE TITLE
When using turbo_stream helpers, the helper proxy is unavailable 

### ISSUE THREAD

**Issue by hms** [joeldrapper/phlex#483]
At least if I did everything correctly.....

  <%= turbo_stream.append 'target', Views::Item.new(item: item).call %>

which was the only way I was able to convince the turbo_stream helper to do it's thing with the Phlex class.  Since Phlex objects are just ruby, one can include: SpecificHelper as a work around, but it would be nice if whatever voodoo Rails is requiring could be pushed into the framework.

**Comment by marcoroth** [comment]
This probably belongs to phlex-rails

**Comment by hms** [comment]
Bleh, you are absolutely correct.

Closing and moving.
