### ISSUE TITLE
Attributes cached across view instances

### ISSUE THREAD

**Issue by joelmoss** [joeldrapper/phlex#489]
Perhaps somewhat of an obscure one this, and I am aware that it uses private API's, but...

```ruby
describe Phlex::HTML do
  extend ViewHelper

  describe '__attributes__ override' do
    describe 'first' do
      view do
        def template
          div(identical: 'attribute') { 'one' }
        end
      end

      it 'renders' do
        expect(output).to be == %(<div identical="attribute">one</div>)
      end
    end

    describe 'second' do
      view do
        def __attributes__(**attributes)
          raise 'I should be called'
        end

        def template
          div(identical: 'attribute') { 'one' }
        end
      end

      it 'should raise' do
        expect { output }.to raise_exception StandardError, message: be == 'I should be called'
      end
    end
  end
end
```

The last test case should raise an exception when `__attributes__` is called. But that method is only called on the first test case. I'm assuming because it is cached due to identical attributes between the two tests. However, these two cases describe two different views, so should not share the attribute cache.

If I change the attributes in the second test case, all passes because the attributes are different.

My use case is to allow me to hook into the attributes of any element, and perform additional logic based on the attributes given. It's effectively what we want from https://github.com/joeldrapper/phlex/issues/467

thx

**Comment by joelmoss** [comment]
Yeah I guessed it was intentional. I definately need a proper hook for this. You thought any more in that? Want me to have a go?

**Comment by joeldrapper** [comment]
I’ve been thinking about it. It's quite tricky to do this without breaking the compiler. I also don't really understand why people are doing it. Providing supporting use-cases in #467 would be helpful.

**Comment by joelmoss** [comment]
In the meantime, any suggestions as to how I can work around this?

**Comment by joeldrapper** [comment]
@joelmoss sorry, I can't think of an easy way around this. I’m going to close this issue as it will be considered as part of any implementation of #467.
