### ISSUE TITLE
Block javascript protocol in links

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#5]
If a rails app renders a link from user input, it might be possible for a user to run arbitrary JavaScript on some else's account by using the `javascript:` link protocol. To guard against this Cross Site Scripting (XSS) attack, we should strip `javascript:` from the beginning of the `href` attribute on `<a>` tags.

**Comment by alexandreruban** [comment]
Should we leave `good first issues` to first-time contributors?

In all cases, escaping HTML is a complex topic, and I'm not sure we should do it ourselves in Phlex as it is a ton of work. In Ruby on Rails, the escaping is done in the [rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer) gem that itself depends on [loofah](https://github.com/flavorjones/loofah) that does a *ton* of things to ensure proper sanitization.

Should we instead add a dependency on [rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer) to sanitize the HTML generated by components?

**Comment by joeldrapper** [comment]
@alexandreruban we use ERB utils to escape HTML in tag attributes and text content, which as far as I can tell are the only places where unsafe content could come from.

https://github.com/joeldrapper/phlex/blob/43ae90a788503cdc741d1a1061dd4f78b7bf5a83/lib/phlex/tag.rb#L48
https://github.com/joeldrapper/phlex/blob/43ae90a788503cdc741d1a1061dd4f78b7bf5a83/lib/phlex/text.rb#L10

I opened this issue for the specific case of the `javascript:` protocol in links in case someone renders out a link from user input, though a good content security policy should already protect you from this threat.

> Should we leave good first issues to first-time contributors?
I think so, unless it's blocking some progress. I'd like to close this issue before 1.0 but until then, it's not a big deal.

**Comment by saksham-jain** [comment]
Hey @joeldrapper, I didn't understand the issue properly. If you could explain a bit more, I can pick this up.

**Comment by joeldrapper** [comment]
Hey @saksham-jain I updated the issue with more details. Let me know if there's anything that's not clear from that. One thing to note is someone could try to bypass this stripping by adding it twice, e.g. `javascript:javascript:bad_code`.

**Comment by saksham-jain** [comment]
@joeldrapper should we hard code href attribute or there can be some other attribute we may need to include in this?

**Comment by joeldrapper** [comment]
This can be hard-coded. It’s only relevant to the `href` attribute on `a` tags.
