### ISSUE TITLE
Feature request: `Phlex::HTML#render_to_string` method

### ISSUE THREAD

**Issue by hangsu** [joeldrapper/phlex#508]
Would you consider adding a convenience method that's equivalent to `capture { render SomeComponent.new(...) }`?

Sometimes it’s useful to have a component like `CurrencyComponent.new(cents: 500)`, but used in string interpolation like `"This costs #{CurrencyComponent.new(cents:500).render_to_string}"`

Understandable if you'd rather not.

**Comment by joelmoss** [comment]
I would argue that a component would be overkill for something like that, especially considering it simply returns a string. Just use a method.

**Comment by joeldrapper** [comment]
The `call` method renders a component to a string, but the component won't have access to the view context.

**Comment by joeldrapper** [comment]
@hangsu I’m closing this as already implemented, but ping back if I’ve missed something.
