### ISSUE TITLE
Shorter `component` method

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#55]
It might be worth either renaming the `component` method or giving it a short alias. A few options that come to mind:

1. `comp`, `com` or even `c`
2. `render` or `draw`
3. `view`

**Comment by joeldrapper** [comment]
Another option might be to define a method for the component class name.

```ruby
def template
  NavComponent do
    NavItemComponent "Home", "/"
    NavItemComponent "About", "/about"
    NavItemComponent "Contact", "/contact"
  end
end
```

One downside with this is you would need to use an empty set of parens if you weren't passing any arguments or blocks to the component.

```ruby
def template(&)
  head { ... }
  body {
    HeaderComponent()
    content(&)
    FooterComponent()
  }
end

**Comment by fractaledmind** [comment]
I'm not sure how performant it is, but you should be able to define `const_missing` on the `Phlox::Component` class such that:
```ruby
def template(&)
  head { ... }
  body {
    HeaderComponent
    content(&)
    FooterComponent
  }
end
```
could work (with `const_missing` taking the name of the constant, getting the class object, and then calling `()` on it).

However, if that noticeably hurts performance, `Component()` or `Component[]` isn't bad.

**Comment by joeldrapper** [comment]
I’m pretty sure it won't be missing though as the constant will exist.

**Comment by fractaledmind** [comment]
Ah. I was presuming that Ruby would sort-of walk up the lexical scopes, and so if `Bar` was defined on the global scope, but called within a method inside of `Foo`, then `Foo.const_missing` would be called before then finding `Bar` in the next scope up.

However, I just did a quick test in a console and that isn't true. Disregard.

**Comment by joeldrapper** [comment]
@alexandreruban and I worked on this and got it basically finished before we realised symbols can't contain `:`.

**Comment by joeldrapper** [comment]
I wonder if we should do this to stay really consistent with ViewComponent and ActionView.

```ruby
def template
  render NavComponent.new {
    render Nav::ItemComponent.new("Home", "/")
    render Nav::ItemComponent.new("About", "/about")
    render Nav::ItemComponent.new("Contact", "/contact")
  }
end
```

**Comment by joeldrapper** [comment]
I tried the above and it didn't work because we can't easily capture the context for the Phlex::Block. Let's just stick with `component` for now.
