### ISSUE TITLE
Allow javascript scheme for a tag's href attribute

### ISSUE THREAD

**Issue by gregmolnar** [joeldrapper/phlex#98]
You seem to strip javascript from the `href` attribute here: https://github.com/joeldrapper/phlex/blob/main/lib/phlex/context.rb#L81, and I know it is to prevent XSS, but it is actually a legit requirement to be able to use the javascript scheme there, but the developer need to know it is dangerous. 
I think it should be configurable at minimum, so one can allow javascript if needed.

**Comment by joeldrapper** [comment]
I agree we could add a configuration option but I think we should disallow JavaScript in tag attributes by default. It's not a good idea to use JavaScript like this anyway IMO and it should be disallowed by your CSP too.

**Comment by joeldrapper** [comment]
Perhaps we could allow unsafe attributes like this?

```ruby
def template
  a.allow_dangerous_attributes "Hello", href: "javascript:alert(1)"
end
```

**Comment by joeldrapper** [comment]
Here’s a list of attributes we should probably ban by default. https://www.w3schools.com/tags/ref_eventattributes.asp

**Comment by gregmolnar** [comment]
I wouldn't allow any attributes, just the href of the a tag should be allowed to use the schemes the specification permits. If there would be an `allow_dangerous_attributes` that would allow more than what I would feel comfortable with. IMHO it should be specific to that attribute.

**Comment by joeldrapper** [comment]
But the idea is you wouldn't use `allow_dangerous_attributes` with an unsafe splat, e.g. `a.allow_dangerous_attributes **attributes_from_user_input`.

**Comment by gregmolnar** [comment]
> But the idea is you wouldn't use `allow_dangerous_attributes` with an unsafe splat, e.g. `a.allow_dangerous_attributes **attributes_from_user_input`.

Ah, you are right.
